# -*- mode: ruby -*-
# vi: set ft=ruby :

$script_hosts = <<-SCRIPT
echo '192.168.56.11 serveur1-cluster'>> /etc/hosts
echo '192.168.56.12 serveur2-cluster'>> /etc/hosts
SCRIPT

$script_stats_haproxy = <<-SCRIPT
echo 'listen stats'>>/etc/haproxy/haproxy.cfg
echo '  bind :9999'>>/etc/haproxy/haproxy.cfg
echo '  mode http'>>/etc/haproxy/haproxy.cfg
echo '  stats enable'>>/etc/haproxy/haproxy.cfg
echo '  stats hide-version'>>/etc/haproxy/haproxy.cfg
echo '  stats uri /stats'>>/etc/haproxy/haproxy.cfg
SCRIPT

Vagrant.configure("2") do |config|
  # Number of nodes to provision
  numNodes = 2

  # IP Address Base for private network
  ipAddrPrefix1 = "192.168.56.1"


  # Define Number of RAM for each node
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--groups", "/S9-pfe"]
    v.customize ["modifyvm", :id, "--cpus", "1"]
    v.customize ["modifyvm", :id, "--memory", 1024]
  end

  # Provision Config for each of the nodes
  1.upto(numNodes) do |num|
    nodeName = ("Serveur-" + num.to_s).to_sym
    config.vm.define nodeName do |node|
      node.vm.host_name = nodeName
      node.vm.box = "debian/bullseye64"
      node.vm.network :private_network, ip: ipAddrPrefix1 + num.to_s
      node.vm.provider "virtualbox" do |v|
          v.name = "Serveur-" + num.to_s
      end
      node.vm.provision "shell", inline: $script_hosts
      node.vm.provision "shell", path: "scripts/install_sys.sh"
      node.vm.provision "shell", path: "scripts/install_web.sh"
      node.vm.provision "shell", path: "scripts/install_conf.sh"
      node.vm.provision "shell", inline: $script_stats_haproxy
    end
  end
  config.vm.define "Serveur-2" do |clust|
    clust.vm.provision "shell", path: "scripts/install_cluster.sh"
  end
end
