{
 "title": "System monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Data recieved",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"X\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"apps.plugin\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"audio\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"auth\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"charts.d.plugin\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"cron\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"dns\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"ebpf.plugin\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"gnome\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"go.d.plugin\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"gui\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"kernel\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"khugepaged\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"ksmd\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"logs\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"modem\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"mua\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"netdata\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"netmanager\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"nfacct.plugin\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"other\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"packagemanager\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"print\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"python.d.plugin\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"system\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"tc-qos-helper\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"time\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"timedb\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"webbrowser\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_recv_kilobits_persec_average{chart=\"apps.total_bandwidth_recv\", dimension=\"wifi\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netdata_cpu_cpu_percentage_average{chart=\"cpu.cpu0\", dimension=\"user\", family=\"utilization\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"X\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"apps.plugin\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"audio\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"auth\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"charts.d.plugin\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"cron\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"dns\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"ebpf.plugin\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"gnome\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"go.d.plugin\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"gui\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"kernel\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"khugepaged\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"ksmd\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"logs\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"modem\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"mua\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"netdata\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"netmanager\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"nfacct.plugin\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"other\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"packagemanager\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"print\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"python.d.plugin\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"system\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"tc-qos-helper\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"time\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"timedb\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"webbrowser\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "netdata_apps_total_bandwidth_sent_kilobits_persec_average{chart=\"apps.total_bandwidth_sent\", dimension=\"wifi\", family=\"net\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netdata_system_uptime_seconds_average{chart=\"system.uptime\", dimension=\"uptime\", family=\"uptime\", instance=\"localhost:19999\", job=\"netdata-scrape\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}