# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|  
    # Customize machine
    config.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--cpus", "1"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--groups", "/PFE"]
    end
  
    # Provision Config
    config.vm.define "controller" do |machine|
        machine.vm.host_name = "srv-controller"
        machine.vm.box = "debian/bullseye64"
        machine.vm.network :public_network
        # machine.vm.network :public_network
        machine.vm.provider "virtualbox" do |v|
            v.name = "controller-1"
        end
        machine.vm.provision "shell", path: "scripts/install_sys.sh"
        machine.vm.provision "shell", path: "scripts/install_web.sh"
        machine.vm.provision "shell", path: "scripts/install_grafana.sh"
        machine.vm.provision "shell", path: "scripts/install_tomcat.sh"
        machine.vm.provision "shell", path: "scripts/install_docker.sh"
    end
end
  